### PR TITLE
Fun

### PR DESCRIPTION
**Pull request by warrenharris**
Here's a first attempt at function definitions. It mostly works, but has the problem that if export is called within a function it won't mark the variable as exported in the global context. I'd like to fix that in a subsequent change. Also, I'm setting up the function context by runStateT and copying/modifying the current state. I'm not sure this is entirely correct, and probably won't work if I get a chance to implement lambda that carry their own context.

Also, I'm not quite sure of my changes to the lexer. I had to make {}() be nonWordChars, otherwise } was being seen as a word... but maybe they should be operators? BTW, what would you think about using Text.Parsec.Language for the lexer? I think it would be really cool to support {- -} style comments that nest (maybe we could use #( ... )# syntax for them).

Also, on the git front I had some problems that I don't understand. First I pulled Evan's for branch, then created my own fun branch, then pushed them to my warren-plush repo, then edited locally, and finally tried to push again. This told me that both for and fun pushes were rejected because of non-fast-forward. So I pulled them down, and ended up with merge conflicts in both of them that I had to resolve (from where - I don't know). Anyway, you'll see that my fun branch has 2 commits on it instead of one because of this.

Warren

### CODE REVIEW

**Comment by warrenharris** [comment]
Hmmm... I meant that for mzero. Clearly I'm a github neophyte. :-)

**Comment by mzero** [comment]
Can you rebase this on master now? master now has Evan's for implementation, and reading the diff for this without that will be much easier. I can't really reconstruct your history with git, so not really sure how you had that all happen. In any event, you should be able to rebase your work off of master, and have something that has no merges at all, and simply "flows off HEAD" into your "fun" branch.

Text.Parsec.Language is too inflexible. It has it's own ideas of how tokens should be parsed, whereas POSIX has a very intricate definition that we must adhere to strictly. Once rebased, I'll review the lexer changes - that is an area full of eels!

**Comment by warrenharris** [comment]
Hmmm... I rebased on master, had the same "non-fast-forward" problem again, fixed that, and we're back to my changes in one commit, and an empty "merge conflict" as a secondary commit. Plus this time, somehow my changes ended up with Evan's name on them. Not sure how that happened. Evan: I guess you own them now!  :-)

**Comment by mzero** [comment]
SUMMARY: I think I'd like to take this in several steps: adding arguments (`$1` etc...), cleaning up `Execute.hs`, and finally parsing and executing functions.

I agree that the execute function via `runStateT` isn't really right, but okay for now... so long as we leave ourselves a big TODO

Finally, I think I can do all the restructuring and git magic... but I'm pretty sure you'll loose the authorship of the change. I think your git mistake was that after you rebased (at 09ae6f4): when you went to push fun back, you should have forced it, rather than let it talk you into a merge. Now, how the rebase came to be Evan's change... can't tell!

You will make things happier if you prune your old branches both locally and from github.

**Comment by warrenharris** [comment]
I'm happy to make the changes in steps and as you suggest, or if you want to take this over, that's no problem too. If I make another attempt, I think I'd start by making a new branch so we can avoid the attribution problem. Maybe we could figure out a day to get together and work on this, figure out a solution to the dummy command executer etc.

BTW, I tried dropping the branches in my local tree and pushing that to github, but nothing seemed to be removed there.

**Comment by mzero** [comment]
I'm mostly done refactoring this into what turned out to be five separate changes - I'll push soon and we can all have one more once over.

**Comment by mzero** [comment]
Reorganized and merged in at fdaaa74

**Pull request closed without merging**
